name:                 IC-Haskell
version:              0.1.0.0
visibility:           public
id:                   IC-Haskell-0.1.0.0-inplace
key:                  IC-Haskell-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           kevin.quimatzoyaro@gmail.com
author:               Kevin
abi:                  inplace
exposed:              True
exposed-modules:      ArvoreBinaria.Arvore MyLib
import-dirs:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/build"

library-dirs:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/build"

library-dirs-static:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/build"

dynamic-library-dirs:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/build"

data-dir:             "/home/kevin/Documents/IC Haskell/."
hs-libraries:         HSIC-Haskell-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/doc/html/IC-Haskell/IC-Haskell.haddock"

haddock-html:
    "/home/kevin/Documents/IC Haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/IC-Haskell-0.1.0.0/doc/html/IC-Haskell"
